[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/v1/system/health/ready"
healthcheckTimeout = 120
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 5
